### ISSUE TITLE
Erro na hora de fazer o download de todos os capítulos

### ISSUE THREAD

**Issue by pilaco** [CleysonPH/manga-downloader#1]
Olá.
Ao tenta fazer o download de todos os capítulos do mangá Toradora descobrir que alguns mangás tem _letras_ e não apenas números.
```
python3 mangadownloader.py --manga toradora --all
Chapter must be a number

```
![image](https://user-images.githubusercontent.com/22872431/73410377-c7c67100-42e0-11ea-85ed-29d05ca47da0.png)

Você poderia fazer com que script aceita-se não só  apenas números, mas tembém _letras_?

**Comment by CleysonPH** [comment]
Fiz uma rápida atualização no código para permitir baixar capítulos que não contenham apenas números no nome, porém isso vai fazer com que o link de ir para o próximo capitulo no HTML que é gerado para ler os mangás não funcione em alguns casos.

**Comment by pilaco** [comment]
Muito obrigado!
